### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by buttt5460** [mviereck/dockerfile-x11docker-deepin#1]
Log:

backend_syslog.go: 45: < info> syslog is not available: Unix syslog delivery error
backend_syslog.go: 45: < info> syslog is not available: Unix syslog delivery error
backend_syslog.go: 45: < info> syslog is not available: Unix syslog delivery error
backend_syslog.go: 45: < info> syslog is not available: Unix syslog delivery error
<waming> main.go: 77: empty display string

**Comment by mviereck** [comment]
Can you please provide the command you have used, and the full terminal output, too?

**Comment by buttt5460** [comment]
Synology
docker pull x11docker/deepin
Cannot start after pulling the image, do I need parameters?

**Comment by mviereck** [comment]
The image `x11docker/deepin` is designed for and tested with [x11docker](https://github.com/mviereck/x11docker).
`synology` is a different container application than `docker`. 
I can't tell how to use `synology` to run a desktop. Likely it would be difficult.

On how to use `x11docker/deepin` with `x11docker`, look at [README.md](https://github.com/mviereck/dockerfile-x11docker-deepin/blob/master/README.md).
