### ISSUE TITLE
Why do you use this setting in Dockerfile: apt-mark hold iptables?

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#10]
Hi,

I noticed that you hold back the iptables in the Dockerfile [here](https://github.com/mviereck/dockerfile-x11docker-deepin/blob/74dc1f36eebc3def48f9df7ee25e0dbb38c6132f/Dockerfile#L40). But I really can't understand why you did this. 

Any hints will be highly appreciated.

Regards,
HY

**Comment by mviereck** [comment]
I once had issues updating `iptables` during `docker build` and the build failed.
 IIRC iptables needs some capabilities that are disabled by default in docker, and/or apt tried to restart it and failed.

**Comment by hongyi-zhao** [comment]
I created an image including iptables with this [Dockerfile](https://github.com/hongyi-zhao/dockerfile/blob/master/deepin/Dockerfiles/deepin-wine) and it can run smoothly without any problem when starting by the following command:

`$ x11docker --sudouser -c --hostnet --keepcache --desktop --init=systemd -- --cap-add=ALL --security-opt seccomp=unconfined -- hongyi-zhao/deepin-wine startdde`

**Comment by mviereck** [comment]
You should never use `--cap-add=ALL` as a solution for anything. It is a security leak. If at all, try to find the one capability that is needed, read about it and assess if it is worth the security risk.
Edit: The worst and most dangerous capability is `SYS_ADMIN`.
