### ISSUE TITLE
x11docker ERROR: No container command specified and no CMD or ENTRYPOINT found in image.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#17]
The docker image is created with the [Dockerfile](https://github.com/hongyi-zhao/docker-deepin/blob/master/Dockerfile/deepin) using the following command in the repo's top level subdirectory:

`$ docker build --network host -f Dockerfile/deepin . -t hongyi-zhao/deepin`

But it can't be started. See following for more info:  

```
$ x11docker --desktop --init=systemd --hostnet -- --cap-add=IPC_LOCK --security-opt seccomp=unconfined -- hongyi-zhao/deepin
x11docker WARNING: User werner is member of group docker.
  That allows unprivileged processes on host to gain root privileges.

x11docker note: Using X server option --xephyr

x11docker note: Xephyr is a quite stable nested X server.
  Less stable, but resizeable is nxagent with option --nxagent.

x11docker WARNING: Option --hostnet severly degrades 
  container isolation. Network namespacing is disabled. 
  Container shares host network stack. Spying on network traffic may be possible. 
  Access to host X server :1 may be possible through abstract unix socket.

x11docker WARNING: Found custom DOCKER_RUN_OPTIONS.
  x11docker will add them to 'docker run' command without
  a serious check for validity or security. Found options:
   '--cap-add=IPC_LOCK' '--security-opt' 'seccomp=unconfined'

x11docker WARNING: Option --init=systemd slightly degrades container isolation.
  It adds some user switching capabilities x11docker would drop otherwise.
  However, they are still within default docker capabilities.
  Not within default docker capabilities it adds capability SYS_BOOT.  
  It shares access to host cgroups in /sys/fs/cgroup.
  Some processes in container will run as root.


x11docker ERROR: No container command specified and no CMD or ENTRYPOINT found in image.

  Type 'x11docker --help' for usage information
  Debug options: '--verbose' (full log) or '--debug' (log excerpt).
  Logfile will be: /home/werner/.cache/x11docker/x11docker.log
  Please report issues at https://github.com/mviereck/x11docker
```

But the docker image can be started smoothly as follows:

```
$ x11docker --desktop --init=systemd --hostnet -- --cap-add=IPC_LOCK --security-opt seccomp=unconfined -- hongyi-zhao/deepin deepin-terminal

or

$ x11docker --init=systemd --hostnet -- --cap-add=IPC_LOCK --security-opt seccomp=unconfined -- hongyi-zhao/deepin deepin-terminal
```
Why the x11docker designed this way when invoking docker?
 
Regards,
HY

**Comment by mviereck** [comment]
> x11docker ERROR: No container command specified and no CMD or ENTRYPOINT found in image.

The error message exactly means what it says: No command to execute is specified. 
docker would throw an error, too, if you run `docker run hongyi-zhao/deepin`.

In the Dockerfile you have disabled the CMD instruction `CMD startdde`.
So a command has to be specified after the image name as you did in the working `deepin-terminal` example.

**Comment by hongyi-zhao** [comment]
Thanks for pointing this out. I commented out all the CMD instructions when I combine these Dockerfiles into one:
 
```
https://github.com/mviereck/dockerfile-x11docker-deepin/blob/master/Dockerfile
https://github.com/bestwu/docker-deepin/blob/master/amd64/Dockerfile
```
Finally, I forget to uncomment the last CMD instruction. Without the last CMD instruction disabled, it should be equivalent to the following command when don't supply any command to the container:

`$ x11docker --desktop --init=systemd --hostnet -- --cap-add=IPC_LOCK --security-opt seccomp=unconfined -- hongyi-zhao/deepin startdde`

**Comment by mviereck** [comment]
> Finally, I forget to uncomment the last CMD instruction. Without the last CMD instruction disabled, it should be equivalent to the following command when don't supply any command to the container:

Yes.
