### ISSUE TITLE
Can this method run any of the software shipped in the latest Deepin distro?

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#2]
Hi,

Can this method run any of the software shipped in the latest  Deepin distro?

Regards,
HY

**Comment by mviereck** [comment]
Yes, of course. The image is based on and installed from the deepin repository.
Some deepin applications are already installed.
You can add further software in the Dockerfile or generate a new one based on the image.
```
FROM x11docker/deepin
RUN apt-get update && apt-get -y dist-upgrade
RUN apt-get install <packagename>
```

**Comment by hongyi-zhao** [comment]
But the Deepin distro used in [Dockerfile](https://github.com/mviereck/dockerfile-x11docker-deepin/blob/36b3343198a0687b913ef5d767b0a4ec6a712aee/Dockerfile#L34) is panda which is not the latest distro. The current stable release is [lion](http://mirrors.kernel.org/deepin/dists/stable/Release).

**Comment by mviereck** [comment]
> The current stable release is lion.

Indeed. I wasn't aware of this new release, thank you.

I've updated the Dockerfile from `panda` to `lion`. 
Currently a new build is running on docker hub, that will take a while. In about an hour or two the new build should be available.
It would be nice if you check it out if it works well.

**Comment by hongyi-zhao** [comment]
Thanks, I'll check it. BTW, if so, all the partial/specific packages' schema should be retired by this project, say, the following ones:
```
https://github.com/RokasUrbelis/docker-wine-linux
https://github.com/huan/docker-wechat
https://github.com/bestwu/docker-wechat
```

**Comment by mviereck** [comment]
The build has already finished, has been faster than I thought.

> https://github.com/huan/docker-wechat
https://github.com/bestwu/docker-wechat

<s>Currently the image does not include `wechat`, maybe I should add it.</s>
Just noticed that there is no native `wechat` client for linux and it would need wine, too.

> https://github.com/RokasUrbelis/docker-wine-linux

There is already an image `x11docker/lxde-wine`. I would not like to include wine in `x11docker/deepin`, too.


Are there other applications that should be added?
Overall, the image is already quite big and I would like to keep it as small as possible.
Maybe `fcitx-pidgin` should be added to allow additional keyboard configuration.

**Comment by hongyi-zhao** [comment]
IMO, the major reason for which we want to build a docker container based on Deepin is that this distro has so many optimized tools running under wine and the target user group is Chinese. 

Though you can build the wine container based on other distros, say, Debian, but it doesn't mean that you can run the same Windows apps working for Deepin-wine. The Deepin-wine is a specially revised/fixed version which is not the same as the official wine and has the characteristics of maximum compatibility for Windows programs popularly used by Chinese people.

Regards,
HY

**Comment by mviereck** [comment]
I think it might rather make sense to provide `x11docker/deepin` as it is.
It can be used as a base image and extended with desired applications. Other x11docker desktop images follow the same concept and provide only few applications on their own.

The `README.md` could contain an instruction how to extend `x11docker/deepin` for wine applications.
Something like this should work:
```
FROM x11docker/deepin
RUN env DEBIAN_FRONTEND=noninteractive dpkg --add-architecture i386 && apt-get update
RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y \
      deepin-wine deepin-wine32 deepin-wine32-preloader deepin-wine-helper deepin-wine-uninstaller
RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      deepin.com.wechat
```
Could you try this out?

**Comment by hongyi-zhao** [comment]
Thanks a lot for your wonderful work. I'll try it tomorrow. 

BTW, are you a German?

**Comment by mviereck** [comment]
I've pulled the new `x11docker/deepin` image and also build an image with wine and wechat. An explanation is added to the README.
So far I succeeded, everything works as expected. `wechat` starts slow, but after some time it shows a QR code to scan.

The x11docker command to run the image is shorter than before now, some insecure options are no longer needed with deepin lion. That are quite good news.

Installing wine and wechat adds 0.9 GB to the image. So I won't include it in the base image, that is far too much.

There is still an issue left: I cannot switch to chinese keyboard layout. Could you have a look in #3?

> BTW, are you a German?

Yes, I am a German in Germany.

**Comment by hongyi-zhao** [comment]
Very glad to hear your good news.

> There is still an issue left: I cannot switch to chinese keyboard layout. Could you have a look in #3?

I've posted some personal experiences there. Hope that helps.

**Comment by hongyi-zhao** [comment]
Another issue: have you also tried qq, say, deepin.com.qq.im?

**Comment by mviereck** [comment]
I did not try other wine applications so far. You could just try yourself like the wechat example.
