### ISSUE TITLE
The differences between --home and --share options for using with folder.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#21]
The built-in help of x11docker tells the following usages:

```
$ x11docker -h | egrep -A 5 -- '--home |--share '
 -m, --home [=ARG]     Create a persistant HOME folder for data storage.
                       Default: Uses ~/.local/share/x11docker/IMAGENAME.
                       ARG can be another host folder or a Docker volume.
                       (~/.local/share/x11docker has a softlink to ~/x11docker.)
                       (Use --homebasedir to change this base storage folder.)
     --share ARG       Share host file or folder ARG. Read-only with ARG:ro
                       Device files in /dev can be shared, too.
                       ARG can also be a Docker volume instead of a host folder.
```

What's the differences between *--home* and *--share* options for using with folder?

**Comment by mviereck** [comment]
`--home=PATH` will share `PATH` and use it as `HOME` directory. Applications store their configuration in `HOME`.
`--share=PATH` just shares the folder.

**Comment by hongyi-zhao** [comment]
I still feel very confused when using these options. What's the rules of thumb for me to share data between host and containers?

**Comment by mviereck** [comment]
As a rule of thumb, I'd say:
 - Use `--home` if you want to store configurations of applications.
 - Use `--share ~/sharefolder` to share data between host and container.

For example, I run my firefox container with `--home --share=~/Downloads`. So firefox configuration like bookmarks is stored with `--home`, but Downloads are directly accessible in my host Download folder.

**Comment by hongyi-zhao** [comment]
The --home has its default value, i.e., *~/.local/share/x11docker/IMAGENAME*.

```
 -m, --home [=ARG]     Create a persistant HOME folder for data storage.
                       Default: Uses ~/.local/share/x11docker/IMAGENAME.
                       ARG can be another host folder or a Docker volume.
                       (~/.local/share/x11docker has a softlink to ~/x11docker.)
                       (Use --homebasedir to change this base storage folder.)
```

In your example, `--home --share=~/Downloads`, `--home` is used without assigned by any value, does it mean --home will take the default value shown above? If so, why not omit its use from the arguments list?

Regards,
HY

**Comment by mviereck** [comment]
> --home is used without assigned by any value, does it mean --home will take the default value shown above?

Yes

> If so, why not omit its use from the arguments list?

Without option `--home` no host folder will be used for it and the data stored in container home is lost.

**Comment by hongyi-zhao** [comment]
> > --home is used without assigned by any value, does it mean --home will take the default value shown above?
> 
> Yes

Does this mean all the containers referred to the same image will share the same *--home*?

**Comment by mviereck** [comment]
Yes.

**Comment by hongyi-zhao** [comment]
Is this behavior reasonable?

**Comment by mviereck** [comment]
> Is this behavior reasonable?

Well, I'd say so.
For example, I provide an image `x11docker/lxde-wine`.
I can run it as an entire desktop, or I can run single wine applications.
The wine applications are stored in a common `--home` folder identified by the same image name.

**Comment by hongyi-zhao** [comment]
But, even the non-wine applications included in the image can also store in the common --home folder identified by the same image name.

Anyway, it seems that you are right, I mean, for the specific OS distro and release version, we should have similar configurations.

**Comment by hongyi-zhao** [comment]
> For example, I run my firefox container with `--home --share=~/Downloads`. So firefox configuration like bookmarks is stored with `--home`, but Downloads are directly accessible in my host Download folder.

It seems that the following usages are equivalent:

```
--share=~/Downloads
 and
--share ~/Downloads
```

**Comment by mviereck** [comment]
> It seems that the following usages are equivalent:

Yes, they are equivalent. `--share` always takes an argument, so both syntax are unambiguous.
