### ISSUE TITLE
Extend the base deepin image with a different apt repo. 

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#26]
Say, I've created the *hongyi-zhao/deepin* base image with the apt repo "http://packages.deepin.com/deepin/", then I want to make extended images *hongyi-zhao/deepin-wine* based on it but with a different apt repo, say, "http://mirrors.ustc.edu.cn/deepin". Is this reasonable and possible without recreating the base image?

**Comment by mviereck** [comment]
> Is this reasonable and possible without recreating the base image?
@hongyi-zhao

Yes, you already did that. Just replace the entries in `/etc/apt/sources.list` and run `apt-get-update`.
