### ISSUE TITLE
[Solved] The method of extending fcitx with the fcitx-cloudpinyin module for the deepin base image. 

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#31]
I've solved the problem. Both of the following methods can do the trick.

1. Install the fcitx-module-cloudpinyin package shipped in the deepin repo. 

2. Compile the module based on its latest git master source code as following.
 
```
$ sudo apt install build-essential cmake fcitx-libs-dev libcurl4-openssl-dev
$ git clone https://github.com/fcitx/fcitx-cloudpinyin.git fcitx/fcitx-cloudpinyin.git
$ cd fcitx/fcitx-cloudpinyin.git/
$ mkdir build
$ cd build/
$ cmake ..
$ make
$ sudo cp src/fcitx-cloudpinyin.so /usr/lib/x86_64-linux-gnu/fcitx/
```

**Comment by mviereck** [comment]
You could just install the package `fcitx-module-cloudpinyin` instead.

(Side note: I've installed `fcitx-sunpinyin` because it is listed in the recommends of package `dde`.)

**Comment by hongyi-zhao** [comment]
> You could just install the package `fcitx-module-cloudpinyin` instead.

I've learned that this package is too outdated to retrieve the cloud data correctly, so I decide to compile the latest git master version of it.

> (Side note: I've installed `fcitx-sunpinyin` because it is listed in the recommends of package `dde`.)

Thanks for your clarification on the reason for selection this package.

**Comment by hongyi-zhao** [comment]
Another problem is I must manually add sunpinyin into the input method list of the input method configuration UI each time after I entered the container as the screenshot shown below:
 
![image](https://user-images.githubusercontent.com/11155854/100353854-24daa280-302a-11eb-841e-4208a9e3cdfa.png)

Are there some commands/instructions for doing this job in the docker file during the image building progress?

**Comment by mviereck** [comment]
> Are there some commands/instructions for doing this job in the docker file during the image building progress?

It should be possible with providing an fcitx configuration file in `/etc/skel`. Have a look in `~/.config` after you have done your settings in which file the setting is stored. Compare similar attempts in `x11docker/lxde`.

If you run with option `--home`, the setting is stored, too.

On compiling and enabling `cloudpinyin`: This is not an x11docker or x11docker/deepin issue, I don't want to debug this myself.

**Comment by hongyi-zhao** [comment]
> If you run with option --home, the setting is stored, too.

Still not so clear on your above note. Based on the description of the --home option:
```
 -m, --home [=ARG]     Create a persistant HOME folder for data storage.
                       Default: Uses ~/.local/share/x11docker/IMAGENAME.
```
According to my understanding, if I'm using --home without any argument, the ~/.local/share/x11docker/IMAGENAME will be used for persistent data storage. But based my testings, use this option can't let me use the previous settings at all. I'm not sure whether I've understood your meaning correctly.

**Comment by mviereck** [comment]
> But based my testings use this option can't let me use the previous settings automatically. 

It seems the configuration is stored, but running `fcitx` in autostart is not enough.
Likely command `fcitx` must be replaced with `fcitx-autostart` in the `fcitx.desktop` file. I am testing soon.

**Comment by mviereck** [comment]
Fixed!
```

# fcitx: Chinese input support
ENV XMODIFIERS=@im=fcitx QT4_IM_MODULE=fcitx QT_IM_MODULE=fcitx GTK_IM_MODULE=fcitx
RUN apt-get update && \
    env DEBIAN_FRONTEND=noninteractive apt-get install -y \
        fcitx-sunpinyin && \
    mkdir -p /etc/xdg/autostart && \
    echo "[Desktop Entry]\n\
Encoding=UTF-8\n\
Version=0.9.4\n\
Type=Application\n\
Name=fcitx\n\
Comment=\n\
Exec=/usr/bin/fcitx-autostart\n\
" > /etc/xdg/autostart/fcitx.desktop && \
    /cleanup
```
With option `--home` the setting is stored (has been before, too), but now it immediatly works after startup without running the config gui again.

**Comment by hongyi-zhao** [comment]
Do you mean the --home option is needless anymore with the above fix applied?

**Comment by mviereck** [comment]
> Do you mean the --home option is needless anymore with the above fix applied?

No, without `--home` you need to select the input method every time.
With option `--home` your fcitx configuration will be stored.

Edit: deepin seems to have a configuration storage issue. I've opened ticket #32 .

**Comment by hongyi-zhao** [comment]
> Fixed!

I tried to build the docker image with [the latest Dockerfile](https://github.com/hongyi-zhao/dockerfile-x11docker-deepin/blob/master/Dockerfile) which, including this fix, is slightly revised from your latest git master version, but still I must run the config GUI once when startup the container for the first time. See the screenshot as shown below for more info:

![image](https://user-images.githubusercontent.com/11155854/100409943-2f3b8180-30a8-11eb-954c-bac8e6b25c9b.png)

**Comment by hongyi-zhao** [comment]
For fcitx5, fcitx5-module-cloudpinyin is merged into [fcitx5-chinese-addons](https://github.com/fcitx/fcitx5-chinese-addons) as a submodule.
