### ISSUE TITLE
--home: some configuration in deepin control center is lost.

### ISSUE THREAD

**Issue by mviereck** [mviereck/dockerfile-x11docker-deepin#32]
@hongyi-zhao wrote in #31:
> According to my understanding, if I'm using --home without any argument, the ~/.local/share/x11docker/IMAGENAME will be used for persistent data storage. But based my testings, use this option can't let me use the previous settings at all. I'm not sure whether I've understood your meaning correctly.

You understand correctly.
But it seems some configurations in the deepin control center are lost nonetheless. I just tried with language and keyboard settings, they are lost. Other settings like e.g. "dark theme" and mouse cursor theme are stored.

Other things are stored, too, e.g. the application order in the application menu that shows the last used application on top. My fcitx configuration and my configuration of the file manager to show hidden files is stored, too.

I don't know how to fix this. Looks like a deepin bug.

**Comment by hongyi-zhao** [comment]
BTW, the dirty and quick workaround for saving container's changes, say, `--keepcache` and `docker commit` should can persevere all user configurations, in case all other methods failed. But as you have told, it's not the suggested way and not a good practice for production environment.

**Comment by mviereck** [comment]
> --keepcache and docker commit should can persevere all user configurations

If it does, deepin would not store its configuration in `HOME`. That would be wrong behaviour.

**Comment by hongyi-zhao** [comment]
> If it does, deepin would not store its configuration in HOME. That would be wrong behaviour.

It seems that I'm still not understanding the data persistence mechanism of docker to a decent degree. Could you please give me some more detailed explanations on your above assertion?

**Comment by mviereck** [comment]
Basically it is simple:
It is standard that applications store user configurations in `HOME`.
x11docker provides option `--home` to preserve this folder on host.
That's all.

> data persistence mechanism of docker

docker also provides so called "docker volumes" for persistent data storage. x11docker does not use this possibility (except you provide a docker volume with `--home=volumename`).

**Comment by hongyi-zhao** [comment]
Do you mean the current used method is based on [bind mounts](https://docs.docker.com/storage/bind-mounts/) if the supplied argument is not a volumename?

**Comment by mviereck** [comment]
Yes, with docker option `--volume`. Compare the shown docker command if you run x11docker with option `--debug`.

**Comment by mviereck** [comment]
It seems o be a deepin issue that a few configurations in its control center are not stored. Closing issue because it is not caused by x11docker or the image build process.
