### ISSUE TITLE
W: Cannot check Release signature; keyring file not available /usr/share/keyrings/deepin-archive-camel-keyring.gpg

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#34]
I try to build the docker image with [this Dockerfile](https://github.com/hongyi-zhao/dockerfile-x11docker-deepin/blob/master/Dockerfile) which is slightly revised base on your latest git master version, but I still see the following info during the image creating progress: 

`W: Cannot check Release signature; keyring file not available /usr/share/keyrings/deepin-archive-camel-keyring.gpg`

Any hints/comments/fixes for this problem?

Regards,
HY

**Comment by mviereck** [comment]
That is the keyring file that has been provided with `deepin-keyring`  before.
Try to remove line
```
keyring /usr/share/keyrings/deepin-archive-camel-keyring.gpg\n\
```
in the debootstrap script.

**Comment by hongyi-zhao** [comment]
Good catch! I've removed that line from [the Dockerfile](https://github.com/hongyi-zhao/dockerfile-x11docker-deepin/blob/8492756bc4b8dc05951fdb64f2f4a3e7fa325307/Dockerfile#L64).
