### ISSUE TITLE
Deepin apricot: inputting the digits included in password with num keyboard will freeze the qq login.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#35]
I find that, for qq, if inputting the digits included in password with number keyboard, the login UI of qq will freeze and lose response to user's operation.

**Comment by mviereck** [comment]
That looks like a deepin or qq issue.
Run qq in terminal and have a look at the output while typing on the numpad.

**Comment by hongyi-zhao** [comment]
There are so much garbage message displayed on the terminal. I found that sometimes the digits input by the numpad cannot be captured by the QQ login interface, but sometimes they can.

**Comment by mviereck** [comment]
It is unlikely that this issue is related to x11docker or x11docker/deepin.
Just in case you could check if it happens with other X server options, too.
Likely it is a qq or wine issue.

**Comment by hongyi-zhao** [comment]
In any case, this problem will not have a significant impact on actual use, considering that I can use the `--home` option and let qq remember the login credentials for the first time.
