### ISSUE TITLE
The appstore with codename apricot should be used when extending the base Deepin  apricot image.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#38]
The appstore with codename [apricot](https://mirror.deepines.com/testing/appstore/dists/apricot/) already published, so I think it should be used to extend the base Deepin  apricot image instead of with eagle as noted in the [README.md](https://github.com/mviereck/dockerfile-x11docker-deepin#deepin-community-repository).

**Comment by mviereck** [comment]
I just checked:
deepin.com:
 - https://community-store-packages.deepin.com/ throws a 404 error (not found)
 - https://community-store-packages.deepin.com/appstore throws a 403 error (forbidden)
deepines.com:
 - https://mirror.deepines.com/testing/appstore/dists/apricot/ throws a 522 error (Connection timed out)

So it is currently not possible at all to build from a community repository.

**Comment by hongyi-zhao** [comment]
See my testing results:
```
$ curl -o /dev/null -x socks5://127.0.0.1:18888 -I -L -s -w '%{http_code}\n' https://community-store-packages.deepin.com/
404
$ curl -o /dev/null -x socks5://127.0.0.1:18888 -I -L -s -w '%{http_code}\n' https://community-store-packages.deepin.com/appstore
403
$ curl -o /dev/null -x socks5://127.0.0.1:18888 -I -L -s -w '%{http_code}\n' https://mirror.deepines.com/testing/appstore/dists/apricot/
200
$ curl -o /dev/null -x socks5://127.0.0.1:18888 -I -L -s -w '%{http_code}\n' https://mirrors.ustc.edu.cn/deepin/dists/apricot
200
```
I've created [the base Deepin apricot docker hub repo](https://hub.docker.com/repository/docker/hongyizhao/deepin) and [the extended deepin-wine docker hub repo](https://hub.docker.com/repository/docker/hongyizhao/deepin-wine) with the last two Deepin repos shown above referred by the corresponding GitHub Dockerfile repos. The bash hook scripts in the GitHub repo will automatically trigger the Deepin base and extended images building progresses after each commit immediately.

**Comment by mviereck** [comment]
The official repository is still unaccessible with 404.
I've decided to reduce the README.md instruction.
Old content preserved here:

-----------------------
To replace the deepin repository with the community repository, build a new image with:
```
FROM x11docker/deepin

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1C30362C0A53D5BB && \
    echo "deb [by-hash=force] https://community-packages.deepin.com/deepin/ apricot main contrib non-free"  > /etc/apt/sources.list && \
    echo "deb https://community-store-packages.deepin.com/appstore apricot appstore" > /etc/apt/sources.list.d/appstore.list && \
    apt-get update
```

Many deepin wine applications need `i386` architecture support. Add this with:
```
RUN dpkg --add-architecture i386 && apt-get update
```

To install e.g. WeChat add this line:
```
RUN env DEBIAN_FRONTEND=noninteractive apt-get install -y com.qq.weixin.deepin && apt-get clean
```
WeChat can be started in container with: `/opt/apps/com.qq.weixin.deepin/files/run.sh`. To let it appear in the application menu, add:
```
RUN cp /opt/apps/com.qq.weixin.deepin/entries/applications/com.qq.weixin.deepin.desktop /usr/share/applications/
```
