### ISSUE TITLE
File transfer with wechat in Deepin paricot docker container started through x11docker using bridge network is inefficient and unstable.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#39]
I noticed that the file transfer with wechat in Deepin paricot docker container started through x11docker using bridge network is inefficient and unstable, which will be fixed by `--hostnet` option. The file used for the testing is created by the following method:

`$ dd if=/dev/urandom of=file.txt count=90 bs=1048576`

**Comment by mviereck** [comment]
The difference might be related to your special proxy setup.

**Comment by hongyi-zhao** [comment]
> The difference might be related to your special proxy setup.

I've tried with curl to download a huge Debian install DVD ISO image with/without proxy in the container for the bridge case, but the observed speed is excellent for both.

**Comment by mviereck** [comment]
Than I have no idea why wechat has a problem. After all, and as your test with curl shows, it is a wechat issue.
