### ISSUE TITLE
FROM bestwu/deepin:lion and FROM x11docker/deepin

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#4]
Hi,

The following code is given in [README.md](https://github.com/mviereck/dockerfile-x11docker-deepin/blob/master/README.md#extend-base-image):

`FROM x11docker/deepin
`

But you use the following setting in [Dockerfile](https://github.com/mviereck/dockerfile-x11docker-deepin/blob/74dc1f36eebc3def48f9df7ee25e0dbb38c6132f/Dockerfile#L26):

`FROM bestwu/deepin:lion`

I'm still confused on the above two docker commands. Why you use different sources for *FROM*?

Regards,
HY

**Comment by mviereck** [comment]
The image `bestwu/deepin:lion` does not contain the deepin desktop but only a core system. 

The Dockerfile for `x11docker/deepin` installs the deepin desktop and a few deepin applications.

If one wants more than the already given applications on the deepin desktop, they can be added using the `x11docker/deepin` image as a base.
