### ISSUE TITLE
About the echo command used for multiple lines case in the Dockerfile.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#41]
I've learned that the Dockerfile itself don't support heredoc and also noticed that you use the echo command as a candidate solution for multiple lines heredoc case in the Dockerfile of this repo, say, the following ones:

```
# cleanup script for use after apt-get
RUN echo '#! /bin/sh\n\
env DEBIAN_FRONTEND=noninteractive apt-get autoremove -y\n\
apt-get clean\n\
find /var/lib/apt/lists -type f -delete\n\
find /var/cache -type f -delete\n\
find /var/log -type f -delete\n\
exit 0\n\
' > /rootfs/cleanup && chmod +x /rootfs/cleanup
```
 
and

```
# debootstrap script
RUN mkdir -p /usr/share/debootstrap/scripts && \
    echo "mirror_style release\n\
download_style apt\n\
finddebs_style from-indices\n\
variants - buildd fakechroot minbase\n\
. /usr/share/debootstrap/scripts/debian-common \n\
" > /usr/share/debootstrap/scripts/$DEEPIN_RELEASE
```

Some notes for using echo with the above codes:

1. Why not add `-n` option of echo to disable the appending of a newline at the end?
2. You sometimes use single quote, sometimes double quote. Why not uniformly use double quote combination with the `-e` option of echo to do the job as shown below:

```
$ echo -en "#!/bin/sh\n\
env DEBIAN_FRONTEND=noninteractive apt-get autoremove -y\n\
apt-get clean\n\
find /var/lib/apt/lists -type f -delete\n\
find /var/cache -type f -delete\n\
find /var/log -type f -delete\n\
exit 0\n\
" 
#! /bin/sh
env DEBIAN_FRONTEND=noninteractive apt-get autoremove -y
apt-get clean
find /var/lib/apt/lists -type f -delete
find /var/cache -type f -delete
find /var/log -type f -delete
exit 0
```

**Comment by mviereck** [comment]
> Why not add -n option of echo to disable the appending of a newline at the end?

I don't want to disable it for `echo`. The \ at the end disables newline for `docker build`.

> You sometimes use single quote, sometimes double quote. 

Both ways are ok, I have no preference. If using variables it makes a difference.

> Why not uniformly use double quote combination with the -e option of echo to do the job as shown below:

Where does `-e` make a difference?

**Comment by hongyi-zhao** [comment]
> I don't want to disable it for echo. The \ at the end disables newline for docker build.

Still not so clear on your above explanation. Any more hints?

> Where does -e make a difference?

The above option is just one of my trial and error. Sorry for my insufficient understanding on the mechanism of executing commands/creating a script using a single line string for multiline purpose from within the Dockerfile. 

Based on the following notes/comments/tricks/discussions/explanations:

1. https://www.tutorialfor.com/blog-274404.htm 
2. https://stackoverflow.com/questions/33439230/how-to-write-commands-with-multiple-lines-in-dockerfile-while-preserving-the-new
3. https://mihamina.rktmb.org/2016/06/dockerfile-multiline-to-file.html   
4. https://github.com/moby/moby/issues/1799

It seems the following usage is more robust and convenient:

```
SHELL ["/bin/bash", "-c"]
RUN echo $"command substitute `hostname -i` \n\
#comment line \n\
variable expanding or not: \$HOME $HOME \n\
single and double quote: ' \"
" > blabla
```

Some people also suggest to use printf for this type of job, as it has more powerful capability than echo.

**Comment by mviereck** [comment]
> It seems the following usage is more robust and convenient:

I don't see an advantage.

> >   I don't want to disable it for echo. The \ at the end disables newline for docker build.

> Still not so clear on your above explanation. Any more hints?

`docker build` can only read one line. `\` disables the newline and allows to read multiple lines.  Without this the build would fail, just try out.
To get newlines with `echo` in the resulting file I add `\n`.

**Comment by hongyi-zhao** [comment]
BTW, are the following two instructions equivalent?
```
SHELL ["/bin/bash", "-c"]
ENV SHELL=/bin/bash
```

**Comment by mviereck** [comment]
> BTW, are the following two instructions equivalent?

No. I've never used the `SHELL` instruction myself, please look at the docker documentation for insight.
