### ISSUE TITLE
Disscussion on the environment variables setting of fcitx5 once more.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#45]
I noticed the notes given [here](https://peeweep.de/2019/07/16/archlinux-fcitx5-config/) about the environment variables setting of fcitx5 as shown below:

wayland: ~/.pam_environment

```
GTK_IM_MODULE=fcitx5
QT_IM_MODULE=fcitx5
XMODIFIERS="@im=fcitx5"
```
x11: ~/.xprofile
```
export GTK_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
export QT_IM_MODULE=fcitx5
fcitx5 &
```
As you can see, the above settings will trigger the starting of fcitx5 for the x11 case in the `~/.xprofile` but for the wayland case doesn't. I'm very confused on this. Any hints?

Regards,
HY

**Comment by mviereck** [comment]
I doubt that fcitx will run under Wayland at all because it uses X server technology.

Aside from that, Wayland will never run `~/.xprofile` because it is not an X server.
You could run the commands in `~/.bashrc` instead.

**Comment by hongyi-zhao** [comment]
What is the difference between using `~/.xprofile` or `~/.bashrc` for this case?

**Comment by mviereck** [comment]
This is something you could easily research on your own.
`~./xprofile` is started on X startup, `~/.bashrc` is started on bash startup.

**Comment by hongyi-zhao** [comment]
Based on the [notes](https://www.csslayer.info/wordpress/fcitx-dev/fcitx5-on-flatpak/) given by the author of fcitx, the environment variables should be set ~/.xprofile, ~/.bashrc, ~/.profile, or some other similar places with the following form:
```
export QT_IM_MODULE=fcitx
export GTK_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
```
