### ISSUE TITLE
The strange garbled Chinese character display problem for qq and fcitx-googlepinyin.

### ISSUE THREAD

**Issue by hongyi-zhao** [mviereck/dockerfile-x11docker-deepin#49]
The fcitx-googlepinyin and qq are installed in the docker image for deepin apricot. See [here](https://github.com/hongyi-zhao/dockerfile/tree/master/x11docker-deepin-wine) for the detailed info.

But I noticed a very strange Chinese garbled code display problem for qq when uisng the fcitx-googlepinyin to input Chinese characters. The relevant areas are marked and numbered as shown on the following screenshot. As you can see, the input results on the region 2 are garbled, but they are displayed correct on other regions, say, 1 and 3. 

![image](https://user-images.githubusercontent.com/11155854/104279950-19faa500-54e6-11eb-905d-ac0f9dd6daa9.png)

WeChat does not have this problem. Any hints/comments/suggestions/fixes are highly appreciated.

Regards,
HY

**Comment by mviereck** [comment]
I can hardly say anything about this. I am not familiar with pidgin in general or googlepinyin in special.
I recommend to ask the googlepinyin developers.

If you assume this is an x11docker bug, please test googlepinyin outside of x11docker, i.e. install and try on your host system for comparision. If the same issue occurs on host, it is not an x11docker issue.
