### ISSUE TITLE
Use centos7 to cause build failure? [udisks2 dpkg error]

### ISSUE THREAD

**Issue by wnark** [mviereck/dockerfile-x11docker-deepin#52]
![image](https://user-images.githubusercontent.com/24355466/161263710-1ae02155-6455-4ca9-8c78-9ab7b0f0a5de.png)
Failed to disable unit, unit dbus-com.deepin.lastore.service does not exist.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
<info> upgradable.go:218: stat /etc/apt/sources.list.d/security.list: no such file or directory
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
E: lstat /lastore/override/desktop2uaid: no such file or directory
Setting up dde-api (5.5.12-1) ...
Adding user deepin-sound-player to group audio
Created symlink /etc/systemd/system/multi-user.target.wants/deepin-login-sound.service → /lib/systemd/system/deepin-login-sound.service.
Created symlink /etc/systemd/system/graphical.target.wants/deepin-shutdown-sound.service → /lib/systemd/system/deepin-shutdown-sound.service.
Setting up gcr (3.28.1-1) ...
Setting up pinentry-gnome3 (1.1.0-2+rb2) ...
Setting up gnome-keyring (3.28.2-5) ...
Setting up dde-daemon (5.14.18-1) ...
update-alternatives: using /usr/lib/deepin-daemon/default-terminal to provide /usr/bin/x-terminal-emulator (x-terminal-emulator) in auto mode
Created symlink /etc/systemd/system/graphical.target.wants/deepin-accounts-daemon.service → /lib/systemd/system/deepin-accounts-daemon.service.
Setting up startdde (5.9.15.1-1) ...
update-alternatives: using /usr/bin/startdde to provide /usr/bin/x-session-manager (x-session-manager) in auto mode
Setting up dde-dock (5.5.12-1) ...
Setting up dde-clipboard (5.15.0102.7-1) ...
Setting up dde-launcher (5.5.11-1) ...
Setting up dde-control-center (5.5.16.2-1) ...
Processing triggers for initramfs-tools (0.137.35-1+dde) ...
Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.38.1+dfsg-1) ...
Processing triggers for libc-bin (2.28.19-1+dde) ...
Processing triggers for dbus (1.12.20-0+deb10u1+rebuild) ...
Errors were encountered while processing:
 udisks2
 gvfs-daemons
 gvfs-backends
 libdde-file-manager:amd64
 dde-desktop
 gvfs:amd64
 dde-file-manager
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get update &&     env DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends         dde-control-center         dde-clipboard         dde-desktop         dde-dock         dde-file-manager         dde-kwin         dde-launcher         dde-qt5integration         deepin-artwork         deepin-default-settings         deepin-desktop-base         deepin-wallpapers         fonts-noto         startdde &&     /cleanup' returned a non-zero code: 100

**Comment by wnark** [comment]
[deepin.log](https://github.com/mviereck/dockerfile-x11docker-deepin/files/8397703/deepin.log)

**Comment by mviereck** [comment]
Thank you for the report!
Meanwhile I've tried to build myself and get the same errors. I'll have a look at this.

**Comment by mviereck** [comment]
I could track down the issue to an `udisks2` postinstall error.
I have included an ugly workaround that removes the postinstall script of udisks2. This should do no harm as the udisks2 systemd service is disabled by x11docker.
The build succeeds now.

**Comment by hongyi-zhao** [comment]
This is exactly the same as the issue discussed [here](https://github.com/hongyi-zhao/dockerfile/issues/1
). And I came up with a [solution](https://github.com/hongyi-zhao/dockerfile/blob/7a2d04aad7969b2c20e0936c2a70201cd74ba6dc/deepin/desktop/Dockerfile#L68) similar to [yours](https://github.com/mviereck/dockerfile-x11docker-deepin/commit/727e146265157714f9d8b3474bc09213f474a80b):

```shell
RUN apt-get -y update && \
    env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends --no-install-suggests \
        udisks2 || \
        rm /var/lib/dpkg/info/udisks2* && \
        dpkg --configure -a && \
        env DEBIAN_FRONTEND=noninteractive apt -f install
```
N.B.: The udisks2 repository is located [here](https://github.com/storaged-project/udisks).
