### ISSUE TITLE
debian bootstrap configuration delayed

### ISSUE THREAD

**Issue by yjqg6666** [mviereck/dockerfile-x11docker-deepin#53]
> Step 4/20 : RUN apt-get update &&     env DEBIAN_FRONTEND=noninteractive apt-get install -y         debootstrap          gnupg &&     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 425956BB3E31DF51 &&     mkdir -p /rootfs/etc/apt &&     cp /etc/apt/trusted.gpg /rootfs/etc/apt/trusted.gpg &&     echo "deb     $DEEPIN_MIRROR $DEEPIN_RELEASE main non-free contrib" > /rootfs/etc/apt/sources.list &&     echo "deb-src $DEEPIN_MIRROR $DEEPIN_RELEASE main non-free contrib" >> /rootfs/etc/apt/sources.list
> ...
> debconf: delaying package configuration, since apt-utils is not installed

**Comment by yjqg6666** [comment]
@mviereck PTAL.

**Comment by mviereck** [comment]
Thank you for the report and your pull request!
The missing `apt-utils` package does not harm the installation except throwing a warning.
And in the second step the debian layer (now including `apt-utils`) is entirely replaced by the deepin system that was downloaded with `debootstrap`.
However, I'll merge your pull request.
